BASIC_BIOS = [
    "Always cooking, rarely following the recipe.",
    "My measuring spoon is my heart ❤️",
    "If garlic is wrong, I don't want to be right 🧄",
    "Turned my kitchen into a lab and I’m not sorry 🧪🍳",
    "Can I interest you in 6 versions of the same chili?",
    "Cooking is cheaper than therapy, and tastier.",
    "Leftovers are a lifestyle, not a mistake.",
    "Cooking dinner while planning tomorrow’s lunch.",
    "Only here for the snacks and chaos.",
    "Flavor before everything 🔥",
    "My spice cabinet is an emotional support system.",
    "Yes, I plate my instant ramen. Why? Because I can.",
    "Your non-stick pan is shaking.",
    "Trained by TikTok, certified by my tastebuds.",
    "Seasoned with sass, salt, and a little paprika.",
    "Meal prep? More like vibe prep.",
    "Running on caffeine and culinary curiosity ☕️🍝",
    "I burn toast, but I make a mean shakshuka.",
    "Gourmet...ish.",
    "Don’t ask how long it took. Just eat it.",
    "I once made a 4-layer cake out of boredom.",
    "My kitchen = my dojo 🍜🥋",
    "Still learning, still saucing.",
    "Cooking without a timer is my kind of thrill.",
    "Knife skills? Questionable. Flavor skills? Unmatched.",
    "Experimenting with food like it’s jazz.",
    "Dinner party dreamer. Midnight snacker.",
    "I bake when I’m sad. You’ve been warned.",
    "Loyal to my cast iron. Unapologetically.",
    "Living for fusion food and good vibes.",
    "One day I'll learn to measure ingredients. Today is not that day.",
    "My stove and I are in a long-term relationship.",
    "Catch me inventing fake holidays just to cook something new.",
    "I season until the ancestors say stop.",
    "No one: Me: 'Let’s make croissants at midnight!'",
    "Don’t follow me for accuracy, follow me for chaos.",
    "Kitchen gremlin with a flair for fire.",
    "Living proof that burnt edges are still tasty.",
    "Sauce enthusiast. That’s it. That’s the bio.",
    "Everything is better with butter.",
    "If it has cheese, I’m in.",
    "Trying to recreate grandma’s mole with vibes alone.",
    "Fermentation station in the laundry room. Don't ask.",
    "Minimal cleanup is a myth I no longer chase.",
    "My apron has pockets. I win.",
    "One-man food truck operating from a small apartment.",
    "Obsessed with soups. Even in the summer.",
    "Food critic in my head. Disaster artist in reality.",
    "My kitchen has no rules — only snacks.",
    "Just here to stir the pot 🥄😉"
]